### ISSUE TITLE
Export of missing files

### ISSUE THREAD

**Issue by SpitzbartAnna** [emt-project/emt-more-missing-docs#1]
Please reexport  45_9_0493 and 45_9_0495, content of the files is missing.

**Comment by csae8092** [comment]
closed with https://github.com/emt-project/emt-working-data/commit/3f175b2d4d3bb3e697d1fe123c9324262d9b6985 and https://github.com/emt-project/emt-working-data/commit/acf2dc59b524469c2c1c7c05b116cf111cd8b850
